# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml ./
COPY src ./src
COPY README.md ./

# Install dependencies and the package
RUN pip install --no-cache-dir .

# Use a non-root user for security
USER nobody

# Set entrypoint to run the basedosdados MCP main via asyncio
ENTRYPOINT ["python", "-m", "basedosdados_mcp.main"]
CMD []
