# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

# Copy project files
COPY . .

# Install build dependencies and the package
RUN pip install --upgrade pip setuptools wheel \
    && pip install .

# Default to using the MCP stdio entrypoint
ENTRYPOINT ["basedosdados-mcp"]
